batch_size: 4
lr: 0.0001  # learning rate
epochs: 100
weight_decay: 1e-4
lr_scheduler: 'ReduceLROnPlateau'  # choices: StepLR, ExponentialLR, CosineAnnealingLR, ReduceLROnPlateau
gamma: 0.1  # gamma for learning rate scheduler
plateau_patience: 5  # patience for ReduceLROnPlateau
plateau_threshold: 1e-2  # threshold for ReduceLROnPlateau
dropout_rate: 0.15
# Early stopping parameters
early_stopping_patience: 10
early_stopping_delta: 5e-4
# Other parameters
disable_cuda: false
# Model-specific parameters
model: 'swin'  # choices: resnet, vit, gin, moe
pretrained: false
pretrained_model: 'swin_small' # swin_small or swin_base
gpu_id: 7
# Paths for training and saving results
# train_images: '/home/wangzh/hydro_channel/hydro_channel/dataset/hydrofig'
# train_annotations: '/home/wangzh/hydro_channel/hydro_channel/dataset/hydrofile.csv'
train_images: '/home/wangzh/hydro_channel/hydro_channel/dataset/sampling_800'
train_annotations: '/home/wangzh/hydro_channel/hydro_channel/dataset/sampling_800.csv'
log_path: '/home/wangzh/hydro_channel/hydro_channel/experiments/swin/logs/train_log.txt'
test_images_folder: '/home/wangzh/hydro_channel/hydro_channel/dataset/test_images'
random_images_folder: '/home/wangzh/hydro_channel/hydro_channel/dataset/randomfig_11000'
